POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "ricrd",
  "name": "Adam d",
  "password": "ric",
  "gender": "male",
  "location": "Detroit"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}
richar45d@123
###
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richar45d@3@123",
  "newPassword": "richar45dty@123"
}